---
title: "Understanding Sequencing Raw Data"
output: html_document
---

# Understanding Sequencing Raw Data

## Shell and Unix commands
<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSavPAPY3WXe2EiqaRXJmAajFTeGcRbD1qJq4Sp4YlcF1_m7I1X89D1uC-8jDDGinqFLNO2oJNALbNx/embed?start=false&loop=false&delayms=3000" frameborder="0" width="760" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>


### Common Linux Commands


redirect command ">"
pipe command "|"

```{bash, eval=FALSE}
man <COMMAND>
```

```{bash, eval=FALSE}
ls .
```

```{bash, eval=FALSE}
cd
```

```{bash, eval=FALSE}
cat

zcat
```


```{bash, eval=FALSE}
grep
```


```{bash, eval=FALSE}
more
```


```{bash, eval=FALSE}
mkdir
```


```{bash, eval=FALSE}
wget
```


### Lab 1a

  - check the your present directory
    - <code> pwd </code>
  - make a directory called data
    - <code> mkdir data </code>
  - change into data directory
    - <code> cd data </code>
  - check manual page of wget command
    - <code> man wget </code>
  - redirect wget maunual page output into a file called wget.txt
    - <code> man wget > wget.txt </code>
  - return the lines that contain output in the wget.txt file
    - <code> cat wget.txt | grep output </code> OR
    - <code> grep -i output wget.txt </code>



## File formats

  - bcl
  - fastq
  - bam
  - mtx, tsv
  - hdf5 (.h5, .h5ad)

## Public data repositories

### Cellranger/10x

#### Lab 1b

  - Create data directory
  - get 10x PBMC data
  - unzip data
  - explore directory
  - explore files

```{bash, echo = FALSE, eval = FALSE}
mkdir data
wget https://s3-us-west-2.amazonaws.com/10x.files/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz -O data/pbmc3k_filtered_gene_bc_matrices.tar.gz
cd data; tar -xzf pbmc3k_filtered_gene_bc_matrices.tar.gz
cd ..
```




### GEO

 - https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE81905


#### Lab 1c

**Get GEO Data**
  - ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE81nnn/GSE81905/matrix/GSE81905-GPL19057_series_matrix.txt.gz
  - ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE81nnn/GSE81905/matrix/GSE81905-GPL17021_series_matrix.txt.gz


 - make a directory for the files
 - go into that directory
 - get files and place them in the directory
 - View files (try keeping in compressed format and view that way)
 
 
### Single Cell Portal

  - https://portals.broadinstitute.org/single_cell

  - Study: Salk Institute - Single-cell Methylome Sequencing Identifies Distinct Neuronal Populations in Mouse Frontal Cortex

#### Lab 1d

  - Get R2 fastq file from the Salk Institute study 
  - Look at files
